Removed Timber for logging and replaced with Log
thunderbiscuit/padawan-wallet pull request #117
Opened 2021-07-26 10:52 UTC by mbcse

2021-07-29 14:14 UTC, thunderbiscuit commented
Only two small comments:

1. Do you mind removing the dependency on Timber in the `app/build.gradle.kts` file? (line 85)
2. I see that you upgraded the Android Gradle plugin. It's a good idea but doesn't belong in this PR (also as a side note, this property is defined in the `buildSrc/src/main/kotlin/Dependencies.kt` file, and so that's where you'd go and fix it to 4.2.2). I assume this might have been done by your IDE as a recommendation and you just clicked "yes" to the upgrade. Not a problem at all but do you mind bringing it back to what it was before I merge? We'll upgrade it in a new commit.

2021-07-29 14:16 UTC, thunderbiscuit commented on build.gradle.kts
> +        classpath("com.android.tools.build:gradle:4.2.2")
This should be rolled back to the old line 
```gradle
classpath("com.android.tools.build:gradle:${Versions.androidGradlePlugin}")
```

See PR message for explanations (we'll upgrade the plugin in a different commit).

2021-07-29 14:17 UTC, thunderbiscuit requested changes
Good work! See small comment.

2021-07-30 05:32 UTC, mbcse commented
> Good work! See small comment.

Done!

2021-07-30 13:45 UTC, merged

2021-07-30 13:45 UTC, thunderbiscuit commented
Thanks a bunch!